[package]
name = "iced_drop"
version = "0.1.0"
edition = "2024"
rust-versio = "1.88"

[dependencies]
iced.workspace = true

[workspace.dependencies]
iced = { version = "0.14", features = ["advanced"] }

[workspace]
members = ["examples/*"]
